import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex:1, alignItems:'center', justifyContent:'center' },
  bgLight: { backgroundColor: '#F9FAFB' },
  bgDark: { backgroundColor: '#0F1724' },
  deviceMockup: { width: 380, height: 820, borderRadius: 36, overflow:'hidden', backgroundColor:'#fff', padding:16, ...Platform.select({ web: { boxShadow: '0 12px 30px rgba(15,23,36,0.12)' }, default: { shadowColor: '#000', elevation: 6 } }) },
  screenContainer: { flex:1, padding:12 },
  topRightToggle: { position:'absolute', right:18, top:18 },
  themeButton: { padding:8, backgroundColor:'#F3F4F6', borderRadius:999 },
  themeText: { fontSize:16 },
  onboardCenter: { flex:1, alignItems:'center', justifyContent:'center' },
  onboardTitle: { fontSize:22, fontWeight:'700', marginBottom:8 },
  onboardDesc: { color:'#6B7280', textAlign:'center', marginBottom:16 },
  onboardIconWrapper: { padding:20, borderRadius:20, backgroundColor:'#FFF4EF' },
  onboardFooter: { paddingBottom:12 },
  stepIndicatorRow: { flexDirection:'row', justifyContent:'center', marginBottom:12 },
  stepDot: { width:10, height:10, borderRadius:10, backgroundColor:'#E5E7EB', marginHorizontal:6 },
  stepDotActive: { backgroundColor:'#FF6B35' },
  onboardButtonsRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center' },
  ghostButton: { padding:10 },
  primaryButton: { backgroundColor:'#FF6B35', padding:12, borderRadius:14 },
  primaryButtonText: { color:'#fff', fontWeight:'700' },

  authTitle: { fontSize:28, fontWeight:'800', textAlign:'center', marginTop:24 },
  authToggleRow: { flexDirection:'row', alignSelf:'center', marginTop:24, borderRadius:12, overflow:'hidden' },
  authTab: { paddingVertical:8, paddingHorizontal:20, backgroundColor:'#F3F4F6' },
  authTabActive: { backgroundColor:'#FFEDD5' },
  authForm: { marginTop:20, paddingHorizontal:6 },
  input: { backgroundColor:'#fff', padding:12, borderRadius:12, marginVertical:8, borderWidth:1, borderColor:'#E5E7EB' },
  passwordRow: { flexDirection:'row', alignItems:'center' },
  eyeButton: { padding:8, marginLeft:8 },

  appWrapper: { flex:1, justifyContent:'flex-end' },
  appBody: { flex:1 },
  tabBar: { height:72, backgroundColor:'#fff', borderRadius:36, flexDirection:'row', alignItems:'center', justifyContent:'space-around', paddingHorizontal:12, marginVertical:8, ...Platform.select({ web: { boxShadow: '0 8px 20px rgba(15,23,36,0.08)' }, default: { shadowColor: '#000', elevation: 6 } }) },
  tabButton: { alignItems:'center', justifyContent:'center' },
  tabButtonActive: { transform:[{translateY:-6}] },
  tabIcon: { marginBottom:4 },
  tabLabel: { fontSize:12, color:'#6B7280' },

  fabWrap: { position:'absolute', left:'50%', marginLeft:-36, bottom:40 },
  fab: { width:72, height:72, borderRadius:36, backgroundColor:'#FF6B35', alignItems:'center', justifyContent:'center', ...Platform.select({ web: { boxShadow: '0 10px 28px rgba(15,23,36,0.12)' }, default: { shadowColor: '#000', elevation: 8 } }) },

  pageScroll: { paddingBottom:120 },
  headerRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom:12 },
  greeting: { color:'#6B7280', includeFontPadding: true },
  username: { fontSize:20, fontWeight:'700', includeFontPadding: true },
  avatar: { width:48, height:48, borderRadius:24 },

  balanceCard: { backgroundColor:'#FFEDD8', borderRadius:20, padding:12, marginBottom:12 },
  balanceHeaderRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom:6 },
  balanceLabel: { color:'#6B7280' },
  smallPill: { backgroundColor:'#FF6B35', paddingHorizontal:8, paddingVertical:4, borderRadius:10 },
  balanceAmount: { fontSize:26, fontWeight:'800', marginBottom:6 },
  incomeExpenseRow: { flexDirection:'row', justifyContent:'space-between' },
  inOutBlock: { width:'48%', backgroundColor:'#fff', padding:8, borderRadius:12, alignItems:'center' },
  inOutText: { color:'#6B7280' },
  inOutAmount: { fontWeight:'700' },

  section: { marginVertical:8 },
  sectionTitle: { fontWeight:'700', marginBottom:8, includeFontPadding: true },
  barChartRow: { flexDirection:'row', alignItems:'flex-end', justifyContent:'space-between', height:180, paddingHorizontal:6 },
  bar: { width:28, backgroundColor:'#E5E7EB', borderRadius:6 },

  txRow: { flexDirection:'row', alignItems:'center', paddingVertical:8 },
  txIcon: { width:44, height:44, borderRadius:22, alignItems:'center', justifyContent:'center', marginRight:12 },
  txTitle: { fontWeight:'600', includeFontPadding: true },
  txMeta: { color:'#6B7280', fontSize:12, includeFontPadding: true },
  txAmount: { fontWeight:'700', includeFontPadding: true },

  pageInner: { flex:1, padding:12 },
  stickyRow: { flexDirection:'row', alignItems:'center', marginBottom:8 },
  searchInput: { flex:1, backgroundColor:'#fff', padding:10, borderRadius:12, borderWidth:1, borderColor:'#E5E7EB' },
  filterBtn: { padding:10, marginLeft:8, backgroundColor:'#fff', borderRadius:12 },
  txGroup: { marginBottom:12 },
  groupTitle: { fontWeight:'700', marginBottom:8 },

  monthBudgetCard: { backgroundColor:'#fff', padding:12, borderRadius:12 },
  progressTrack: { height:8, backgroundColor:'#F3F4F6', borderRadius:8, overflow:'hidden' },
  progressFill: { height:8, backgroundColor:'#10B981' },

  budgetCard: { backgroundColor:'#fff', padding:12, borderRadius:12, flexDirection:'row', alignItems:'center', marginBottom:8 },
  budgetIcon: { fontSize:24, marginRight:12 },
  dashedButton: { borderWidth:1, borderStyle:'dashed', borderColor:'#D1D5DB', padding:12, borderRadius:12, alignItems:'center', marginTop:8 },

  profileHeader: { flexDirection:'row', alignItems:'center', marginBottom:12 },
  profileAvatar: { width:76, height:76, borderRadius:38, marginRight:12 },
  proBadge: { marginTop:6, backgroundColor:'#FF6B35', paddingHorizontal:8, paddingVertical:4, borderRadius:8 },

  settingsSection: { backgroundColor:'#fff', padding:12, borderRadius:12, marginBottom:12 },
  settingsRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', paddingVertical:8 },
  settingsGroup: { backgroundColor:'#fff', borderRadius:12, overflow:'hidden' },
  menuRow: { flexDirection:'row', justifyContent:'space-between', padding:12, borderBottomWidth:1, borderColor:'#F3F4F6' },
  menuText: { includeFontPadding: true },

  modalBackdrop: { flex:1, backgroundColor:'rgba(0,0,0,0.35)', justifyContent:'flex-end' },
  modalCard: { backgroundColor:'#fff', padding:16, borderTopLeftRadius:16, borderTopRightRadius:16 },
  modalHeader: { flexDirection:'row', justifyContent:'space-between', alignItems:'center' },
  typeToggle: { padding:8, borderRadius:10, borderWidth:1, borderColor:'#E5E7EB', marginHorizontal:8 },
  amountInput: { fontSize:32, fontWeight:'800', textAlign:'center', marginVertical:12 },
});

export default styles;
